apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-test
  name: dev-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dev-test
  template:
    metadata:
      labels:
        app: dev-test
    spec:
      containers:
      - image: nginx:1.27.4
        name: nginx
