apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rolling-test
  name: rolling-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rolling-test
  template:
    metadata:
      labels:
        app: rolling-test
    spec:
      containers:
        - image: nginx:1.26.3
          name: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
