apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
    name: nginx-storage
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  volumes: 
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi