apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-mealie
  template:
    metadata:
      labels:
        app: nginx-mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.3.2
          name: mealie
          ports:
            - containerPort: 9000  
