apiVersion: v1
kind: Service
metadata:
  name: mealie
  labels:
    app: mealie
  namespace: mealie
spec:
  selector:
    app: mealie
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  type: LoadBalancer
