# k3d configuration file
apiVersion: k3d.io/v1alpha5
kind: Simple
name: k3d-cluster
image: rancher/k3s:v1.20.4-k3s1
servers: 1 # control plane nodes
agents: 2 # worker nodes
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer