apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    env: test
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
